/**
 * Version: 0.2
 * This file is not to be edited.
*/




export const Timezone: {
  "Pacific/Midway": { zone: "Pacific/Midway", gmt: "(GMT-11:00)", name: "Midway Island" };
  "US/Samoa": { zone: "US/Samoa", gmt: "(GMT-11:00)", name: "Samoa" };
  "US/Hawaii": { zone: "US/Hawaii", gmt: "(GMT-10:00)", name: "Hawaii" };
  "US/Alaska": { zone: "US/Alaska", gmt: "(GMT-09:00)", name: "Alaska" };
  "US/Pacific": { zone: "US/Pacific", gmt: "(GMT-08:00)", name: "Pacific Time (US &amp; Canada)" };
  "America/Tijuana": { zone: "America/Tijuana", gmt: "(GMT-08:00)", name: "Tijuana" };
  "US/Arizona": { zone: "US/Arizona", gmt: "(GMT-07:00)", name: "Arizona" };
  "US/Mountain": { zone: "US/Mountain", gmt: "(GMT-07:00)", name: "Mountain Time (US &amp; Canada)" };
  "America/Chihuahua": { zone: "America/Chihuahua", gmt: "(GMT-07:00)", name: "Chihuahua" };
  "America/Mazatlan": { zone: "America/Mazatlan", gmt: "(GMT-07:00)", name: "Mazatlan" };
  "America/Mexico_City": { zone: "America/Mexico_City", gmt: "(GMT-06:00)", name: "Mexico City" };
  "America/Monterrey": { zone: "America/Monterrey", gmt: "(GMT-06:00)", name: "Monterrey" };
  "Canada/Saskatchewan": { zone: "Canada/Saskatchewan", gmt: "(GMT-06:00)", name: "Saskatchewan" };
  "US/Central": { zone: "US/Central", gmt: "(GMT-06:00)", name: "Central Time (US &amp; Canada)" };
  "US/Eastern": { zone: "US/Eastern", gmt: "(GMT-05:00)", name: "Eastern Time (US &amp; Canada)" };
  "US/East-Indiana": { zone: "US/East-Indiana", gmt: "(GMT-05:00)", name: "Indiana (East)" };
  "America/Bogota": { zone: "America/Bogota", gmt: "(GMT-05:00)", name: "Bogota" };
  "America/Lima": { zone: "America/Lima", gmt: "(GMT-05:00)", name: "Lima" };
  "America/Caracas": { zone: "America/Caracas", gmt: "(GMT-04:30)", name: "Caracas" };
  "Canada/Atlantic": { zone: "Canada/Atlantic", gmt: "(GMT-04:00)", name: "Atlantic Time (Canada)" };
  "America/La_Paz": { zone: "America/La_Paz", gmt: "(GMT-04:00)", name: "La_Paz" };
  "America/Santiago": { zone: "America/Santiago", gmt: "(GMT-04:00)", name: "Santiago" };
  "Canada/Newfoundland": { zone: "Canada/Newfoundland", gmt: "(GMT-03:30)", name: "Newfoundland" };
  "America/Buenos_Aires": { zone: "America/Buenos_Aires", gmt: "(GMT-03:00)", name: "Buenos Aires" };
  "Greenland": { zone: "Greenland", gmt: "(GMT-03:00)", name: "Greenland" };
  "Atlantic/Stanley": { zone: "Atlantic/Stanley", gmt: "(GMT-02:00)", name: "Stanley" };
  "Atlantic/Azores": { zone: "Atlantic/Azores", gmt: "(GMT-01:00)", name: "Azores" };
  "Atlantic/Cape_Verde": { zone: "Atlantic/Cape_Verde", gmt: "(GMT-01:00)", name: "Cape Verde Is." };
  "Africa/Casablanca": { zone: "Africa/Casablanca", gmt: "(GMT)", name: "Casablanca" };
  "Europe/Dublin": { zone: "Europe/Dublin", gmt: "(GMT)", name: "Dublin" };
  "Europe/Lisbon": { zone: "Europe/Lisbon", gmt: "(GMT)", name: "Libson" };
  "Europe/London": { zone: "Europe/London", gmt: "(GMT)", name: "London" };
  "Africa/Monrovia": { zone: "Africa/Monrovia", gmt: "(GMT)", name: "Monrovia" };
  "Europe/Amsterdam": { zone: "Europe/Amsterdam", gmt: "(GMT+01:00)", name: "Amsterdam" };
  "Europe/Belgrade": { zone: "Europe/Belgrade", gmt: "(GMT+01:00)", name: "Belgrade" };
  "Europe/Berlin": { zone: "Europe/Berlin", gmt: "(GMT+01:00)", name: "Berlin" };
  "Europe/Bratislava": { zone: "Europe/Bratislava", gmt: "(GMT+01:00)", name: "Bratislava" };
  "Europe/Brussels": { zone: "Europe/Brussels", gmt: "(GMT+01:00)", name: "Brussels" };
  "Europe/Budapest": { zone: "Europe/Budapest", gmt: "(GMT+01:00)", name: "Budapest" };
  "Europe/Copenhagen": { zone: "Europe/Copenhagen", gmt: "(GMT+01:00)", name: "Copenhagen" };
  "Europe/Ljubljana": { zone: "Europe/Ljubljana", gmt: "(GMT+01:00)", name: "Ljubljana" };
  "Europe/Madrid": { zone: "Europe/Madrid", gmt: "(GMT+01:00)", name: "Madrid" };
  "Europe/Paris": { zone: "Europe/Paris", gmt: "(GMT+01:00)", name: "Paris" };
  "Europe/Prague": { zone: "Europe/Prague", gmt: "(GMT+01:00)", name: "Prague" };
  "Europe/Rome": { zone: "Europe/Rome", gmt: "(GMT+01:00)", name: "Rome" };
  "Europe/Sarajevo": { zone: "Europe/Sarajevo", gmt: "(GMT+01:00)", name: "Sarajevo" };
  "Europe/Skopje": { zone: "Europe/Skopje", gmt: "(GMT+01:00)", name: "Skopje" };
  "Europe/Stockholm": { zone: "Europe/Stockholm", gmt: "(GMT+01:00)", name: "Stockholm" };
  "Europe/Vienna": { zone: "Europe/Vienna", gmt: "(GMT+01:00)", name: "Vienna" };
  "Europe/Warsaw": { zone: "Europe/Warsaw", gmt: "(GMT+01:00)", name: "Warsaw" };
  "Europe/Zagreb": { zone: "Europe/Zagreb", gmt: "(GMT+01:00)", name: "Zagreb" };
  "Europe/Athens": { zone: "Europe/Athens", gmt: "(GMT+02:00)", name: "Athens" };
  "Europe/Bucharest": { zone: "Europe/Bucharest", gmt: "(GMT+02:00)", name: "Bucharest" };
  "Africa/Cairo": { zone: "Africa/Cairo", gmt: "(GMT+02:00)", name: "Cairo" };
  "Africa/Harare": { zone: "Africa/Harare", gmt: "(GMT+02:00)", name: "Harere" };
  "Europe/Helsinki": { zone: "Europe/Helsinki", gmt: "(GMT+02:00)", name: "Helsinki" };
  "Europe/Istanbul": { zone: "Europe/Istanbul", gmt: "(GMT+02:00)", name: "Istanbul" };
  "Asia/Jerusalem": { zone: "Asia/Jerusalem", gmt: "(GMT+02:00)", name: "Jerusalem" };
  "Europe/Kiev": { zone: "Europe/Kiev", gmt: "(GMT+02:00)", name: "Kiev" };
  "Europe/Minsk": { zone: "Europe/Minsk", gmt: "(GMT+02:00)", name: "Minsk" };
  "Europe/Riga": { zone: "Europe/Riga", gmt: "(GMT+02:00)", name: "Riga" };
  "Europe/Sofia": { zone: "Europe/Sofia", gmt: "(GMT+02:00)", name: "Sofia" };
  "Europe/Tallinn": { zone: "Europe/Tallinn", gmt: "(GMT+02:00)", name: "Tallinn" };
  "Europe/Vilnius": { zone: "Europe/Vilnius", gmt: "(GMT+02:00)", name: "Vilnius" };
  "Asia/Baghdad": { zone: "Asia/Baghdad", gmt: "(GMT+03:00)", name: "Baghdad" };
  "Asia/Kuwait": { zone: "Asia/Kuwait", gmt: "(GMT+03:00)", name: "Kuwait" };
  "Africa/Nairobi": { zone: "Africa/Nairobi", gmt: "(GMT+03:00)", name: "Nairobi" };
  "Asia/Riyadh": { zone: "Asia/Riyadh", gmt: "(GMT+03:00)", name: "Riyadh" };
  "Asia/Tehran": { zone: "Asia/Tehran", gmt: "(GMT+03:30)", name: "Tehran" };
  "Europe/Moscow": { zone: "Europe/Moscow", gmt: "(GMT+04:00)", name: "Moscow" };
  "Asia/Baku": { zone: "Asia/Baku", gmt: "(GMT+04:00)", name: "Baku" };
  "Europe/Volgograd": { zone: "Europe/Volgograd", gmt: "(GMT+04:00)", name: "Volgograd" };
  "Asia/Muscat": { zone: "Asia/Muscat", gmt: "(GMT+04:00)", name: "Muscat" };
  "Asia/Tbilisi": { zone: "Asia/Tbilisi", gmt: "(GMT+04:00)", name: "Tbilisi" };
  "Asia/Yerevan": { zone: "Asia/Yerevan", gmt: "(GMT+04:00)", name: "Yerevan" };
  "Asia/Kabul": { zone: "Asia/Kabul", gmt: "(GMT+04:30)", name: "Kabul" };
  "Asia/Karachi": { zone: "Asia/Karachi", gmt: "(GMT+05:00)", name: "Karachi" };
  "Asia/Tashkent": { zone: "Asia/Tashkent", gmt: "(GMT+05:00)", name: "Tashkent" };
  "Asia/Kolkata": { zone: "Asia/Kolkata", gmt: "(GMT+05:30)", name: "Kolkata" };
  "Asia/Kathmandu": { zone: "Asia/Kathmandu", gmt: "(GMT+05:45)", name: "Kathmandu" };
  "Asia/Yekaterinburg": { zone: "Asia/Yekaterinburg", gmt: "(GMT+06:00)", name: "Yekaterinburg" };
  "Asia/Almaty": { zone: "Asia/Almaty", gmt: "(GMT+06:00)", name: "Almaty" };
  "Asia/Dhaka": { zone: "Asia/Dhaka", gmt: "(GMT+06:00)", name: "Dhaka" };
  "Asia/Novosibirsk": { zone: "Asia/Novosibirsk", gmt: "(GMT+07:00)", name: "Novosibirsk" };
  "Asia/Bangkok": { zone: "Asia/Bangkok", gmt: "(GMT+07:00)", name: "Bangkok" };
  "Asia/Jakarta": { zone: "Asia/Jakarta", gmt: "(GMT+07:00)", name: "Jakarta" };
  "Asia/Krasnoyarsk": { zone: "Asia/Krasnoyarsk", gmt: "(GMT+08:00)", name: "Krasnoyarsk" };
  "Asia/Chongqing": { zone: "Asia/Chongqing", gmt: "(GMT+08:00)", name: "Chongqing" };
  "Asia/Hong_Kong": { zone: "Asia/Hong_Kong", gmt: "(GMT+08:00)", name: "Hong Kong" };
  "Asia/Kuala_Lumpur": { zone: "Asia/Kuala_Lumpur", gmt: "(GMT+08:00)", name: "Kuala Lumpur" };
  "Australia/Perth": { zone: "Australia/Perth", gmt: "(GMT+08:00)", name: "Perth" };
  "Asia/Singapore": { zone: "Asia/Singapore", gmt: "(GMT+08:00)", name: "Singapore" };
  "Asia/Taipei": { zone: "Asia/Taipei", gmt: "(GMT+08:00)", name: "Taipei" };
  "Asia/Ulaanbaatar": { zone: "Asia/Ulaanbaatar", gmt: "(GMT+08:00)", name: "Ulaan Bataar" };
  "Asia/Urumqi": { zone: "Asia/Urumqi", gmt: "(GMT+08:00)", name: "Urumqi" };
  "Asia/Irkutsk": { zone: "Asia/Irkutsk", gmt: "(GMT+09:00)", name: "Irkutsk" };
  "Asia/Seoul": { zone: "Asia/Seoul", gmt: "(GMT+09:00)", name: "Seoul" };
  "Asia/Tokyo": { zone: "Asia/Tokyo", gmt: "(GMT+09:00)", name: "Tokyo" };
  "Australia/Adelaide": { zone: "Australia/Adelaide", gmt: "(GMT+09:30)", name: "Adelaide" };
  "Australia/Darwin": { zone: "Australia/Darwin", gmt: "(GMT+09:30)", name: "Darwin" };
  "Asia/Yakutsk": { zone: "Asia/Yakutsk", gmt: "(GMT+10:00)", name: "Yakutsk" };
  "Australia/Brisbane": { zone: "Australia/Brisbane", gmt: "(GMT+10:00)", name: "Brisbane" };
  "Australia/Canberra": { zone: "Australia/Canberra", gmt: "(GMT+10:00)", name: "Canberra" };
  "Pacific/Guam": { zone: "Pacific/Guam", gmt: "(GMT+10:00)", name: "Guam" };
  "Australia/Hobart": { zone: "Australia/Hobart", gmt: "(GMT+10:00)", name: "Hobart" };
  "Australia/Melbourne": { zone: "Australia/Melbourne", gmt: "(GMT+10:00)", name: "Melbourne" };
  "Pacific/Port_Moresby": { zone: "Pacific/Port_Moresby", gmt: "(GMT+10:00)", name: "Port Moresby" };
  "Australia/Sydney": { zone: "Australia/Sydney", gmt: "(GMT+10:00)", name: "Sydney" };
  "Asia/Vladivostok": { zone: "Asia/Vladivostok", gmt: "(GMT+11:00)", name: "Vladivostok" };
  "Asia/Magadan": { zone: "Asia/Magadan", gmt: "(GMT+12:00)", name: "Magadan" };
  "Pacific/Auckland": { zone: "Pacific/Auckland", gmt: "(GMT+12:00)", name: "Auckland" };
  "Pacific/Fiji": { zone: "Pacific/Fiji", gmt: "(GMT+12:00)", name: "Fiji" };
};

export type Timezone = typeof Timezone;
export type TimezoneKey = "Pacific/Midway" | "US/Samoa" | "US/Hawaii" | "US/Alaska" | "US/Pacific" | "America/Tijuana" | "US/Arizona" | "US/Mountain" | "America/Chihuahua" | "America/Mazatlan" | "America/Mexico_City" | "America/Monterrey" | "Canada/Saskatchewan" | "US/Central" | "US/Eastern" | "US/East-Indiana" | "America/Bogota" | "America/Lima" | "America/Caracas" | "Canada/Atlantic" | "America/La_Paz" | "America/Santiago" | "Canada/Newfoundland" | "America/Buenos_Aires" | "Greenland" | "Atlantic/Stanley" | "Atlantic/Azores" | "Atlantic/Cape_Verde" | "Africa/Casablanca" | "Europe/Dublin" | "Europe/Lisbon" | "Europe/London" | "Africa/Monrovia" | "Europe/Amsterdam" | "Europe/Belgrade" | "Europe/Berlin" | "Europe/Bratislava" | "Europe/Brussels" | "Europe/Budapest" | "Europe/Copenhagen" | "Europe/Ljubljana" | "Europe/Madrid" | "Europe/Paris" | "Europe/Prague" | "Europe/Rome" | "Europe/Sarajevo" | "Europe/Skopje" | "Europe/Stockholm" | "Europe/Vienna" | "Europe/Warsaw" | "Europe/Zagreb" | "Europe/Athens" | "Europe/Bucharest" | "Africa/Cairo" | "Africa/Harare" | "Europe/Helsinki" | "Europe/Istanbul" | "Asia/Jerusalem" | "Europe/Kiev" | "Europe/Minsk" | "Europe/Riga" | "Europe/Sofia" | "Europe/Tallinn" | "Europe/Vilnius" | "Asia/Baghdad" | "Asia/Kuwait" | "Africa/Nairobi" | "Asia/Riyadh" | "Asia/Tehran" | "Europe/Moscow" | "Asia/Baku" | "Europe/Volgograd" | "Asia/Muscat" | "Asia/Tbilisi" | "Asia/Yerevan" | "Asia/Kabul" | "Asia/Karachi" | "Asia/Tashkent" | "Asia/Kolkata" | "Asia/Kathmandu" | "Asia/Yekaterinburg" | "Asia/Almaty" | "Asia/Dhaka" | "Asia/Novosibirsk" | "Asia/Bangkok" | "Asia/Jakarta" | "Asia/Krasnoyarsk" | "Asia/Chongqing" | "Asia/Hong_Kong" | "Asia/Kuala_Lumpur" | "Australia/Perth" | "Asia/Singapore" | "Asia/Taipei" | "Asia/Ulaanbaatar" | "Asia/Urumqi" | "Asia/Irkutsk" | "Asia/Seoul" | "Asia/Tokyo" | "Australia/Adelaide" | "Australia/Darwin" | "Asia/Yakutsk" | "Australia/Brisbane" | "Australia/Canberra" | "Pacific/Guam" | "Australia/Hobart" | "Australia/Melbourne" | "Pacific/Port_Moresby" | "Australia/Sydney" | "Asia/Vladivostok" | "Asia/Magadan" | "Pacific/Auckland" | "Pacific/Fiji";
